In [1]:
import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt

# データセット
import seaborn as sns
sns.set(style="ticks")
df = sns.load_dataset("iris")
print(df)

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]


In [2]:
from sklearn import datasets, model_selection, svm, metrics
iris = datasets.load_iris()

print(type(iris))
print(iris.keys())

<class 'sklearn.utils.Bunch'>
dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])


In [3]:
iris_data = pd.DataFrame(data=iris.data, columns=iris.feature_names)
print(iris_data.head())

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2


In [4]:
iris_label = pd.Series(data=iris.target)
print(iris_label.head())

0    0
1    0
2    0
3    0
4    0
dtype: int32


In [5]:
print(len(iris_data))

150


In [6]:
data_train, data_test, label_train, label_test = model_selection.train_test_split(iris_data, iris_label)
print(data_train.head())

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
123                6.3               2.7                4.9               1.8
50                 7.0               3.2                4.7               1.4
136                6.3               3.4                5.6               2.4
80                 5.5               2.4                3.8               1.1
22                 4.6               3.6                1.0               0.2


In [7]:
print(label_train.head())

123    2
50     1
136    2
80     1
22     0
dtype: int32


In [8]:
print(len(data_train), len(data_test))

112 38


In [13]:
clf = svm.SVC()
clf.fit(data_train, label_train)
pre = clf.predict(data_test)

print(type(pre))
print(np.array(label_test))
print(pre)

<class 'numpy.ndarray'>
[2 0 0 2 0 2 2 1 1 2 1 0 2 2 2 1 2 2 2 1 1 2 2 1 0 1 1 1 0 0 1 0 1 2 0 0 2
 2]
[2 0 0 2 0 2 2 1 1 2 1 0 2 2 2 1 2 2 2 1 1 1 2 1 0 1 1 1 0 0 1 0 1 2 0 0 2
 2]


In [10]:
ac_score = metrics.accuracy_score(label_test, pre)
print(ac_score)

0.9736842105263158


In [11]:
# 混合行列を生成
from sklearn.metrics import confusion_matrix
print(confusion_matrix(np.array(label_test), pre, labels=[0, 1, 2]))

[[10  0  0]
 [ 0 12  0]
 [ 0  1 15]]


In [18]:
# 正解率 - accuracy
from sklearn.metrics import accuracy_score
print(accuracy_score(np.array(label_test), pre))
print(np.sum(pre == 0))

0.9736842105263158
10


In [19]:
# 再現率 - recall
from sklearn.metrics import recall_score
rec_score = recall_score(np.array(label_test), pre, average=None)
print(rec_score)

[1.     1.     0.9375]


In [20]:
# 適合率 - presition
from sklearn.metrics import precision_score
pre_score = precision_score(np.array(label_test), pre, average=None)
print(pre_score)

[1.         0.92307692 1.        ]
